### ISSUE TITLE
When used with Lazypipe, Handyman.clean throws "TypeError: dest.on is not a function" if returned array is populated.

### ISSUE THREAD

**Issue by embpdaniel** [kenzanlabs/pipeline-handyman#27]
handyman's clean function returns an array of deleted items. If there were items to delete (the returned array is populated) the error `TypeError: dest.on is not a function` is thrown. If there were not files to delete, no error is thrown and the task completes.

Attempting to make use of handyman.clean like so:

``` javascript
gulp.src(fixtureSrc)
  .pipe(pipelineArchiveDist.clean([fixtureDest + '*.css', fixtureDest + '*.js']))
  .pipe(pipelineArchiveDist.distributeScripts())
  .pipe(gulp.dest(fixtureDest));


//Within pipelineArchiveDist
function clean(path) {
  let stream = lazypipe()
    .pipe(function(){
      return  handyman.clean(path);
    });
  return stream();
}
```

Cc: @obuckley-kenzan @paul-barry-kenzan

**Comment by obuckley-kenzan** [comment]
Thanks @embpdaniel , will review and get back to you

**Comment by paul-barry-kenzan** [comment]
@embpdaniel @obuckley-kenzan 
Is this a bug, or is it simply improper use of `handyman.clean()`? If it's known (and accepted) that the `del` library doesn't use a Stream, but a Promise, and it should be used within a separate task instead of a "piped" method, I feel that `handyman.clean` should have the same understanding. 

Maybe what we need to resolve this issue is a Gulp usage example in the README that covers this? 

Additionally, is Handyman incorrectly labeled as a "pipeline" when it's really just a wrapper around a non-pipeline deletion library, that can be leveraged within a Gulp task?

**Comment by paul-barry-kenzan** [comment]
@thescientist13 
Closing this issue since [Handyman.clean was updated](https://github.com/kenzanlabs/pipeline-handyman#clean) and should be used as a separate non-stream task.
